### ISSUE TITLE
backend logic system 2023

### ISSUE THREAD

**Issue by Kameroni33** [umatt-ece/rpi-controller#1]
We need a functional logic & I/O controller for competition 2023. Most of this system will be based off the existing code [here](https://github.com/umatt-software/rpi-controller-old).

## Tasks:

- [ ] class(es) for reading sensor input
- [ ] class(es) for setting outputs
- [ ] tractor state machine (maybe should be broken up into separate systems, not sure)
