### ISSUE TITLE
FastAPI websockets

### ISSUE THREAD

**Issue by Kameroni33** [umatt-ece/rpi-controller#10]
## Description

A WebSocket is a communication protocol (like http) for bi-direction communication between a server and client. For our project, when the client (the raspberry pi's browser) connects to our server we want to establish a WebSocket connection between it and our FastAPI server. That way we can notify it whenever we need to. Using this WebSocket connection we want to continuously send it the latest values from Redis, and notify it if anything went wrong with our tractor.

To accomplish this we will need a [connection manager](https://github.com/umatt-software/rpi-controller/blob/development/server/services/client_manager.py) as well as [WebSocket endpoints](https://github.com/umatt-software/rpi-controller/blob/development/server/routers/websocket_routes.py). The frontend will handle establishing the connection, as well as processing any data you send to it (but has not been implemented yet, you may need to do a bit of extra work to test this yourself, check out the example in the notes).

## Tasks

The bare minimum requirements for the 2023 server should be:

- [ ] Establish a websocket with the _display_ frontend (Vuex part of it).
- [ ] Recover from a disconnect (ie. be able to reconnect the socket on the frontend's request).
- [ ] Continuously send the frontend JSON data from Redis (live/stored data).

In the future we should expand the functionality to include:

- [ ] Establish multiple client connections and keep track of them using UUIDs.

## Notes

As a helpful resource check out the example from the documentation [here](https://fastapi.tiangolo.com/advanced/websockets/)
