### ISSUE TITLE
FastAPI endpoints

### ISSUE THREAD

**Issue by Kameroni33** [umatt-ece/rpi-controller#11]
## Description

We need a number of endpoints (a function that gets run when a particular API call is made to the server) that the frontend _display_ can call. Ideally we should also create a markdown document as we go to document the backend API interface. All data should be communicated with the frontend via JSON. The [Swagger UI](https://fastapi.tiangolo.com/features/) is a great way to do testing with the endpoints.

To actually get data from Redis, you'll need to implement a _DataStore_ class within your router. The code for that can be found in [data_store.py](https://github.com/umatt-software/rpi-controller/blob/development/database/data_store.py). If you want to play around with it there is a test file I made that should help give you sense of how to use the class which can be found in [test_data_store.py](https://github.com/umatt-software/rpi-controller/blob/development/database/test/test_data_store.py). Note, you'll need to have Docker Desktop installed and make sure the Redis Container is running in order to test it.

## Tasks

Endpoints to implement:
- [ ] get specific live/stored data from Redis
- [ ] get all live/stored data from Redis
- [ ] set live/stored data in Redis
- [ ] etc...

We'll also need some system endpoints, but I don't know what those are going to be yet.
