### ISSUE TITLE
Vue webpages

### ISSUE THREAD

**Issue by Kameroni33** [umatt-ece/rpi-controller#12]
## Description

Ultimately we need to create our frontend user interface. We are going with a web-based application using the VueJs framework. For more details on the specifics of Vue, check out it's [documentation](https://vuejs.org/guide/introduction.html), (particularly the parts regarding components). Our user interface will be comprised of 3 main elements:

- _Header Bar_
- _Control Panel_
- _Display Window_

Within the the _Display Window_ we will have 3 separate pages: _home_, _settings_, and _diagnostics_.

The basic design of the pages is done (rough outline), but there is still a lot that is lacking. Throughout this entire ticket, any visual improvements to the GUI are encouraged! Take inspiration from previous year's designs but by no means does this mean we need to stick to them.

## Tasks
- [ ] Make sure GUI fits to RPi touch display resolution

### Header
- [ ] General GUI improvements

### Control Panel
- [ ] General GUI improvements
- [ ] Link buttons to backend endpoints (also see #9)
- [ ] Possibly find better icons (?)

### Home Page
- [ ] General GUI improvements
- [ ] Update data based on Vuex Store (see #8)

### Settings Page
- [ ] General GUI improvements
- [ ] Update data based on Vuex Store (see #8)
- [ ] Link buttons to backend endpoints (also  see #9)

### Diagnostics Page
- [ ] General GUI improvements
- [ ] Make page scrollable
- [ ] Add icons for data
- [ ] Update data based on Vuex Store (see #8)

## Notes

Below are some images of old interface designs. We don't have to follow the old UI, but it's a good starting point to improve on. One notable change is that the user buttons must be much bigger than in old designs, as they used an external keypad where as we are using the touch screen. Also, since we now have a web-based model we can use a menu bar to navigate between pages (ie. the home/settings/diagnostics buttons are no longer necessary) and thus the number of buttons we need is now just 6, not 8.

## Old UI Designs
![pcb-diagnostics](https://user-images.githubusercontent.com/65875945/225827840-2145a5d8-b4b2-4260-ac0d-aef3bc40eeb2.png)
![pcb-home](https://user-images.githubusercontent.com/65875945/225827841-4017c2d2-6c8a-4613-9949-29c0cfd63deb.png)
![pcb-settings](https://user-images.githubusercontent.com/65875945/225827843-82ab5eb5-a72d-4d8f-9dcb-4210cbf9f738.png)
![py-diagnostic](https://user-images.githubusercontent.com/65875945/225827845-87374dfd-0a98-4788-8b76-631834bf5f2a.PNG)
![py-home](https://user-images.githubusercontent.com/65875945/225827846-e67b5620-1e09-41a6-9eef-74a65d8e193a.PNG)
![py-notify](https://user-images.githubusercontent.com/65875945/225827848-3875c654-1805-48cd-9f0a-3d1985197d61.PNG)
![py-settings](https://user-images.githubusercontent.com/65875945/225827850-a704ef06-7086-4684-bcbc-840a7d1f06fe.PNG)

**Comment by Kameroni33** [comment]
The general color pallete we're aiming for:

E4BA00 (yellow/gold)
5d5757 (dark brown)
60AFFF (blue)
F9F9F6 (white/cream)
C63130 (red)

**Comment by Kameroni33** [comment]
For getting started with this ticket, definitely check out the Vue [documentation](https://vuejs.org/guide/introduction.html). Also maybe check out some YouTube videos or articles about general HTML/CSS/JavaScript. You don't need to know a ton, just be familiar with it.

Clone the repository to your local machine and check out the development branch. Try following the [setup document](https://github.com/umatt-software/rpi-controller/blob/development/documents/Setup.md) and get the frontend running. Also try to get the server running (you'll need to have docker and redis running for that so it's a bit more involved).

Once you have the project running, poke and around and try changing a few things. Change colors with css, add an html element, make a button print "hello" to the web console. Just try to familiarize yourself with the VueJS.

Next take a look at "fetching" and http requests in general. You'll likely want to consult YouTube again check out some of the Vue or JavaScript documentation. Try running the server and making some requests to it. At first you can just use your browser (ex. "http://localhost:8577/sys/get") and then try doing it using JavaScript to fetch data. You'll wanna quickly research "JSON" and what "GET"/"POST" requests are. This will lead you into ticket #9 which is doing data fetching within the BaseService with Axios (remember that documentation and YouTube are your friends).

Lastly, try playing around with the Vuex Store (see ticket #8). Check out the [documentation](https://vuex.vuejs.org/) and try adding new values ("states"), getters, mutators, etc... Once you've got that try displaying those values on various pages by importing Vuex to access them.

If you're feeling brave you can venture into the backend server and play around with that. Adding new routes/endpoint functions, and learning a bit about FastAPI.
