### ISSUE TITLE
backend web server 2023

### ISSUE THREAD

**Issue by Kameroni33** [umatt-ece/rpi-controller#2]
We need a functional backend webserver for competition 2023.

## Tasks

- [ ] endpoints for updating database values [[11](https://github.com/umatt-software/rpi-controller/issues/11)]
- [ ] system endpoints [[11](https://github.com/umatt-software/rpi-controller/issues/11)]
- [ ] client manager [[10](https://github.com/umatt-software/rpi-controller/issues/10)]
- [ ] broadcast database values to frontend [[10](https://github.com/umatt-software/rpi-controller/issues/10)]
- [ ] document API [[11](https://github.com/umatt-software/rpi-controller/issues/11)]
