### ISSUE TITLE
Vuex Store

### ISSUE THREAD

**Issue by Kameroni33** [umatt-ece/rpi-controller#8]
## Description

An introduction to _Vuex_ and _state management patterns_ can be found [here](https://vuex.vuejs.org/).

The vuex store needs to handle all live/stored values from the database files [live_data.py](https://github.com/umatt-software/rpi-controller/blob/main/database/live_data.py) and [stored_data.py](https://github.com/umatt-software/rpi-controller/blob/main/database/stored_data.py) (ideally with containers that can be generated directly from these files using a script, but maybe a job for another day...)

## Tasks

- [ ] live data module
- [ ] stored data module
- [ ] module for system variables (maybe...)
- [ ] update values from backend API

## Notes

Additionally, we need some method of continuously updating these values from our backend API. Our 2 options are:
- query the backend API every # of seconds
- leverage websockets to have the backend broadcast us the values at # interval
