### ISSUE TITLE
Axios Service

### ISSUE THREAD

**Issue by Kameroni33** [umatt-ece/rpi-controller#9]
## Description

My plan was to use Axios (documentation can be found [here](https://axios-http.com/docs/intro)) to create a service to simplify API calls to the backend. Hopefully creating a centralized location for API calls will keep things more organized and easily to read/edit in the future. Originally I called it "BaseService", but I think this would be more appropriately named "BackendService", "apiUtils", or something a bit more descriptive about its use.

## Tasks

Need to implement the following methods:
- [ ] _get(route)_ that returns the data at that route
- [ ] _post(route, data)_ that sets values on the backend
- [ ] additional functions as we need them (ex. establishWebsocket, getLiveData, etc...)
